import React from 'react';
import { createStyles, Theme, makeStyles } from '@material-ui/core/styles';
import AppBar from '@material-ui/core/AppBar';
import CssBaseline from '@material-ui/core/CssBaseline';
import Toolbar from '@material-ui/core/Toolbar';
import Typography from '@material-ui/core/Typography';
import IconButton from '@material-ui/core/IconButton';
import Paper from '@material-ui/core/Paper';
import Fab from '@material-ui/core/Fab';
import List from '@material-ui/core/List';
import ListItem from '@material-ui/core/ListItem';
import ListItemSecondaryAction from '@material-ui/core/ListItemSecondaryAction';
import ListItemText from '@material-ui/core/ListItemText';
import TextField from '@material-ui/core/TextField';
import Order, { OrderItem } from 'models/commerce/Order'
import { useCart } from 'hooks';

const useStyles = makeStyles((theme: Theme) =>
	createStyles({
		text: {
			padding: theme.spacing(2, 2, 0),
		},
		paper: {
			paddingBottom: 50,
		},
		list: {
			marginBottom: theme.spacing(2),
		},
		subheader: {
			backgroundColor: theme.palette.background.paper,
		},
		appBar: {
			top: 'auto',
			bottom: 0,
		},
		grow: {
			flexGrow: 1,
		},
		fabButton: {
			position: 'absolute',
			zIndex: 1,
			top: -30,
			left: 0,
			right: 0,
			margin: '0 auto',
		},
	}),
);

export default () => {
	const classes = useStyles()
	const [cart, isLoading] = useCart()

	return (
		<>
			<Typography className={classes.text} gutterBottom>
				Cart
      </Typography>
			{isLoading ? (
				<>Loading</>
			) : (
					<List className={classes.list}>
						{cart!.items.map((item, index) => {
							return (
								<ListItem button key={index}>
									<ListItemText primary={item.name} secondary={item.caption} />
									<ListItemSecondaryAction>
										<TextField />
									</ListItemSecondaryAction>
								</ListItem>
							)
						})}
					</List>
				)}
		</>
	)
}

// import React from 'react';
// import { createStyles, Theme, makeStyles } from '@material-ui/core/styles';
// import AppBar from '@material-ui/core/AppBar';
// import CssBaseline from '@material-ui/core/CssBaseline';
// import Toolbar from '@material-ui/core/Toolbar';
// import Typography from '@material-ui/core/Typography';
// import IconButton from '@material-ui/core/IconButton';
// import Paper from '@material-ui/core/Paper';
// import Fab from '@material-ui/core/Fab';
// import List from '@material-ui/core/List';
// import ListItem from '@material-ui/core/ListItem';
// import ListItemAvatar from '@material-ui/core/ListItemAvatar';
// import ListItemText from '@material-ui/core/ListItemText';
// import ListSubheader from '@material-ui/core/ListSubheader';
// import Avatar from '@material-ui/core/Avatar';
// import MenuIcon from '@material-ui/icons/Menu';
// import AddIcon from '@material-ui/icons/Add';
// import SearchIcon from '@material-ui/icons/Search';
// import MoreIcon from '@material-ui/icons/MoreVert';

// const messages = [
// 	{
// 		id: 1,
// 		primary: 'Brunch this week?',
// 		secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
// 		person: '/static/images/avatar/5.jpg',
// 	},
// 	{
// 		id: 2,
// 		primary: 'Birthday Gift',
// 		secondary: `Do you have a suggestion for a good present for John on his work
//       anniversary. I am really confused & would love your thoughts on it.`,
// 		person: '/static/images/avatar/1.jpg',
// 	},
// 	{
// 		id: 3,
// 		primary: 'Recipe to try',
// 		secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
// 		person: '/static/images/avatar/2.jpg',
// 	},
// 	{
// 		id: 4,
// 		primary: 'Yes!',
// 		secondary: 'I have the tickets to the ReactConf for this year.',
// 		person: '/static/images/avatar/3.jpg',
// 	},
// 	{
// 		id: 5,
// 		primary: "Doctor's Appointment",
// 		secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
// 		person: '/static/images/avatar/4.jpg',
// 	},
// 	{
// 		id: 6,
// 		primary: 'Discussion',
// 		secondary: `Menus that are generated by the bottom app bar (such as a bottom
//       navigation drawer or overflow menu) open as bottom sheets at a higher elevation
//       than the bar.`,
// 		person: '/static/images/avatar/5.jpg',
// 	},
// 	{
// 		id: 7,
// 		primary: 'Summer BBQ',
// 		secondary: `Who wants to have a cookout this weekend? I just got some furniture
//       for my backyard and would love to fire up the grill.`,
// 		person: '/static/images/avatar/1.jpg',
// 	},
// ];

// const useStyles = makeStyles((theme: Theme) =>
// 	createStyles({
// 		text: {
// 			padding: theme.spacing(2, 2, 0),
// 		},
// 		paper: {
// 			paddingBottom: 50,
// 		},
// 		list: {
// 			marginBottom: theme.spacing(2),
// 		},
// 		subheader: {
// 			backgroundColor: theme.palette.background.paper,
// 		},
// 		appBar: {
// 			top: 'auto',
// 			bottom: 0,
// 		},
// 		grow: {
// 			flexGrow: 1,
// 		},
// 		fabButton: {
// 			position: 'absolute',
// 			zIndex: 1,
// 			top: -30,
// 			left: 0,
// 			right: 0,
// 			margin: '0 auto',
// 		},
// 	}),
// );

// export default function BottomAppBar() {
// 	const classes = useStyles()
// 	const [cart, isLoading] = useCart()

// 	return (
// 		// <Paper square className={classes.paper}>
// 		<>
// 			<Typography className={classes.text} gutterBottom>
// 				Inbox
//       </Typography>
// 			{isLoading ? (
// 				<>Loading</>
// 			) : (
// 					<List className={classes.list}>
// 						{messages.map(({ id, primary, secondary, person }) => (
// 							<ListItem button key={id}>
// 								<ListItemAvatar>
// 									<Avatar alt="Profile Picture" src={person} />
// 								</ListItemAvatar>
// 								<ListItemText primary={primary} secondary={secondary} />
// 							</ListItem>
// 						))}
// 					</List>
// 				)}
// 		</>
// 		// </Paper>
// 	);
// }
