export default
	[
		{ name: "Afghanistan", alpha2: "AF", alpha3: "AFG", number: "4" },
		{ name: "Albania", alpha2: "AL", alpha3: "ALB", number: "8" },
		{ name: "Algeria", alpha2: "DZ", alpha3: "DZA", number: "12" },
		{ name: "American Samoa", alpha2: "AS", alpha3: "ASM", number: "16" },
		{ name: "Andorra", alpha2: "AD", alpha3: "AND", number: "20" },
		{ name: "Angola", alpha2: "AO", alpha3: "AGO", number: "24" },
		{ name: "Anguilla", alpha2: "AI", alpha3: "AIA", number: "660" },
		{ name: "Antarctica", alpha2: "AQ", alpha3: "ATA", number: "10" },
		{ name: "Antigua and Barbuda", alpha2: "AG", alpha3: "ATG", number: "28" },
		{ name: "Argentina", alpha2: "AR", alpha3: "ARG", number: "32" },
		{ name: "Armenia", alpha2: "AM", alpha3: "ARM", number: "51" },
		{ name: "Aruba", alpha2: "AW", alpha3: "ABW", number: "533" },
		{ name: "Australia", alpha2: "AU", alpha3: "AUS", number: "36" },
		{ name: "Austria", alpha2: "AT", alpha3: "AUT", number: "40" },
		{ name: "Azerbaijan", alpha2: "AZ", alpha3: "AZE", number: "31" },
		{ name: "Bahamas", alpha2: "BS", alpha3: "BHS", number: "44" },
		{ name: "Bahrain", alpha2: "BH", alpha3: "BHR", number: "48" },
		{ name: "Bangladesh", alpha2: "BD", alpha3: "BGD", number: "50" },
		{ name: "Barbados", alpha2: "BB", alpha3: "BRB", number: "52" },
		{ name: "Belarus", alpha2: "BY", alpha3: "BLR", number: "112" },
		{ name: "Belgium", alpha2: "BE", alpha3: "BEL", number: "56" },
		{ name: "Belize", alpha2: "BZ", alpha3: "BLZ", number: "84" },
		{ name: "Benin", alpha2: "BJ", alpha3: "BEN", number: "204" },
		{ name: "Bermuda", alpha2: "BM", alpha3: "BMU", number: "60" },
		{ name: "Bhutan", alpha2: "BT", alpha3: "BTN", number: "64" },
		{ name: "Bolivia (Plurinational State of)", alpha2: "BO", alpha3: "BOL", number: "68" },
		{ name: "Bonaire, Sint Eustatius and Saba", alpha2: "BQ", alpha3: "BES", number: "535" },
		{ name: "Bosnia and Herzegovina", alpha2: "BA", alpha3: "BIH", number: "70" },
		{ name: "Botswana", alpha2: "BW", alpha3: "BWA", number: "72" },
		{ name: "Bouvet Island", alpha2: "BV", alpha3: "BVT", number: "74" },
		{ name: "Brazil", alpha2: "BR", alpha3: "BRA", number: "76" },
		{ name: "British Indian Ocean Territory", alpha2: "IO", alpha3: "IOT", number: "86" },
		{ name: "Brunei Darussalam", alpha2: "BN", alpha3: "BRN", number: "96" },
		{ name: "Bulgaria", alpha2: "BG", alpha3: "BGR", number: "100" },
		{ name: "Burkina Faso", alpha2: "BF", alpha3: "BFA", number: "854" },
		{ name: "Burundi", alpha2: "BI", alpha3: "BDI", number: "108" },
		{ name: "Cabo Verde", alpha2: "CV", alpha3: "CPV", number: "132" },
		{ name: "Cambodia", alpha2: "KH", alpha3: "KHM", number: "116" },
		{ name: "Cameroon", alpha2: "CM", alpha3: "CMR", number: "120" },
		{ name: "Canada", alpha2: "CA", alpha3: "CAN", number: "124" },
		{ name: "Cayman Islands", alpha2: "KY", alpha3: "CYM", number: "136" },
		{ name: "Central African Republic", alpha2: "CF", alpha3: "CAF", number: "140" },
		{ name: "Chad", alpha2: "TD", alpha3: "TCD", number: "148" },
		{ name: "Chile", alpha2: "CL", alpha3: "CHL", number: "152" },
		{ name: "China", alpha2: "CN", alpha3: "CHN", number: "156" },
		{ name: "Christmas Island", alpha2: "CX", alpha3: "CXR", number: "162" },
		{ name: "Cocos (Keeling) Islands", alpha2: "CC", alpha3: "CCK", number: "166" },
		{ name: "Colombia", alpha2: "CO", alpha3: "COL", number: "170" },
		{ name: "Comoros", alpha2: "KM", alpha3: "COM", number: "174" },
		{ name: "Congo (the Democratic Republic of the)", alpha2: "CD", alpha3: "COD", number: "180" },
		{ name: "Congo", alpha2: "CG", alpha3: "COG", number: "178" },
		{ name: "Cook Islands", alpha2: "CK", alpha3: "COK", number: "184" },
		{ name: "Costa Rica", alpha2: "CR", alpha3: "CRI", number: "188" },
		{ name: "Croatia", alpha2: "HR", alpha3: "HRV", number: "191" },
		{ name: "Cuba", alpha2: "CU", alpha3: "CUB", number: "192" },
		{ name: "Curaçao", alpha2: "CW", alpha3: "CUW", number: "531" },
		{ name: "Cyprus", alpha2: "CY", alpha3: "CYP", number: "196" },
		{ name: "Czechia", alpha2: "CZ", alpha3: "CZE", number: "203" },
		{ name: "Côte d'Ivoire", alpha2: "CI", alpha3: "CIV", number: "384" },
		{ name: "Denmark", alpha2: "DK", alpha3: "DNK", number: "208" },
		{ name: "Djibouti", alpha2: "DJ", alpha3: "DJI", number: "262" },
		{ name: "Dominica", alpha2: "DM", alpha3: "DMA", number: "212" },
		{ name: "Dominican Republic", alpha2: "DO", alpha3: "DOM", number: "214" },
		{ name: "Ecuador", alpha2: "EC", alpha3: "ECU", number: "218" },
		{ name: "Egypt", alpha2: "EG", alpha3: "EGY", number: "818" },
		{ name: "El Salvador", alpha2: "SV", alpha3: "SLV", number: "222" },
		{ name: "Equatorial Guinea", alpha2: "GQ", alpha3: "GNQ", number: "226" },
		{ name: "Eritrea", alpha2: "ER", alpha3: "ERI", number: "232" },
		{ name: "Estonia", alpha2: "EE", alpha3: "EST", number: "233" },
		{ name: "Eswatini", alpha2: "SZ", alpha3: "SWZ", number: "748" },
		{ name: "Ethiopia", alpha2: "ET", alpha3: "ETH", number: "231" },
		{ name: "Falkland Islands [Malvinas]", alpha2: "FK", alpha3: "FLK", number: "238" },
		{ name: "Faroe Islands", alpha2: "FO", alpha3: "FRO", number: "234" },
		{ name: "Fiji", alpha2: "FJ", alpha3: "FJI", number: "242" },
		{ name: "Finland", alpha2: "FI", alpha3: "FIN", number: "246" },
		{ name: "France", alpha2: "FR", alpha3: "FRA", number: "250" },
		{ name: "French Guiana", alpha2: "GF", alpha3: "GUF", number: "254" },
		{ name: "French Polynesia", alpha2: "PF", alpha3: "PYF", number: "258" },
		{ name: "French Southern Territories", alpha2: "TF", alpha3: "ATF", number: "260" },
		{ name: "Gabon", alpha2: "GA", alpha3: "GAB", number: "266" },
		{ name: "Gambia", alpha2: "GM", alpha3: "GMB", number: "270" },
		{ name: "Georgia", alpha2: "GE", alpha3: "GEO", number: "268" },
		{ name: "Germany", alpha2: "DE", alpha3: "DEU", number: "276" },
		{ name: "Ghana", alpha2: "GH", alpha3: "GHA", number: "288" },
		{ name: "Gibraltar", alpha2: "GI", alpha3: "GIB", number: "292" },
		{ name: "Greece", alpha2: "GR", alpha3: "GRC", number: "300" },
		{ name: "Greenland", alpha2: "GL", alpha3: "GRL", number: "304" },
		{ name: "Grenada", alpha2: "GD", alpha3: "GRD", number: "308" },
		{ name: "Guadeloupe", alpha2: "GP", alpha3: "GLP", number: "312" },
		{ name: "Guam", alpha2: "GU", alpha3: "GUM", number: "316" },
		{ name: "Guatemala", alpha2: "GT", alpha3: "GTM", number: "320" },
		{ name: "Guernsey", alpha2: "GG", alpha3: "GGY", number: "831" },
		{ name: "Guinea", alpha2: "GN", alpha3: "GIN", number: "324" },
		{ name: "Guinea-Bissau", alpha2: "GW", alpha3: "GNB", number: "624" },
		{ name: "Guyana", alpha2: "GY", alpha3: "GUY", number: "328" },
		{ name: "Haiti", alpha2: "HT", alpha3: "HTI", number: "332" },
		{ name: "Heard Island and McDonald Islands", alpha2: "HM", alpha3: "HMD", number: "334" },
		{ name: "Holy See", alpha2: "VA", alpha3: "VAT", number: "336" },
		{ name: "Honduras", alpha2: "HN", alpha3: "HND", number: "340" },
		{ name: "Hong Kong", alpha2: "HK", alpha3: "HKG", number: "344" },
		{ name: "Hungary", alpha2: "HU", alpha3: "HUN", number: "348" },
		{ name: "Iceland", alpha2: "IS", alpha3: "ISL", number: "352" },
		{ name: "India", alpha2: "IN", alpha3: "IND", number: "356" },
		{ name: "Indonesia", alpha2: "ID", alpha3: "IDN", number: "360" },
		{ name: "Iran (Islamic Republic of)", alpha2: "IR", alpha3: "IRN", number: "364" },
		{ name: "Iraq", alpha2: "IQ", alpha3: "IRQ", number: "368" },
		{ name: "Ireland", alpha2: "IE", alpha3: "IRL", number: "372" },
		{ name: "Isle of Man", alpha2: "IM", alpha3: "IMN", number: "833" },
		{ name: "Israel", alpha2: "IL", alpha3: "ISR", number: "376" },
		{ name: "Italy", alpha2: "IT", alpha3: "ITA", number: "380" },
		{ name: "Jamaica", alpha2: "JM", alpha3: "JAM", number: "388" },
		{ name: "Japan", alpha2: "JP", alpha3: "JPN", number: "392" },
		{ name: "Jersey", alpha2: "JE", alpha3: "JEY", number: "832" },
		{ name: "Jordan", alpha2: "JO", alpha3: "JOR", number: "400" },
		{ name: "Kazakhstan", alpha2: "KZ", alpha3: "KAZ", number: "398" },
		{ name: "Kenya", alpha2: "KE", alpha3: "KEN", number: "404" },
		{ name: "Kiribati", alpha2: "KI", alpha3: "KIR", number: "296" },
		{ name: "Korea (the Democratic People's Republic of) ", alpha2: "KP", alpha3: "PRK", number: "408" },
		{ name: "Korea (the Republic of)", alpha2: "KR", alpha3: "KOR", number: "410" },
		{ name: "Kuwait", alpha2: "KW", alpha3: "KWT", number: "414" },
		{ name: "Kyrgyzstan", alpha2: "KG", alpha3: "KGZ", number: "417" },
		{ name: "Lao People's Democratic Republic(the)", alpha2: "LA", alpha3: "LAO", number: "418" },
		{ name: "Latvia", alpha2: "LV", alpha3: "LVA", number: "428" },
		{ name: "Lebanon", alpha2: "LB", alpha3: "LBN", number: "422" },
		{ name: "Lesotho", alpha2: "LS", alpha3: "LSO", number: "426" },
		{ name: "Liberia", alpha2: "LR", alpha3: "LBR", number: "430" },
		{ name: "Libya", alpha2: "LY", alpha3: "LBY", number: "434" },
		{ name: "Liechtenstein", alpha2: "LI", alpha3: "LIE", number: "438" },
		{ name: "Lithuania", alpha2: "LT", alpha3: "LTU", number: "440" },
		{ name: "Luxembourg", alpha2: "LU", alpha3: "LUX", number: "442" },
		{ name: "Macao", alpha2: "MO", alpha3: "MAC", number: "446" },
		{ name: "Madagascar", alpha2: "MG", alpha3: "MDG", number: "450" },
		{ name: "Malawi", alpha2: "MW", alpha3: "MWI", number: "454" },
		{ name: "Malaysia", alpha2: "MY", alpha3: "MYS", number: "458" },
		{ name: "Maldives", alpha2: "MV", alpha3: "MDV", number: "462" },
		{ name: "Mali", alpha2: "ML", alpha3: "MLI", number: "466" },
		{ name: "Malta", alpha2: "MT", alpha3: "MLT", number: "470" },
		{ name: "Marshall Islands", alpha2: "MH", alpha3: "MHL", number: "584" },
		{ name: "Martinique", alpha2: "MQ", alpha3: "MTQ", number: "474" },
		{ name: "Mauritania", alpha2: "MR", alpha3: "MRT", number: "478" },
		{ name: "Mauritius", alpha2: "MU", alpha3: "MUS", number: "480" },
		{ name: "Mayotte", alpha2: "YT", alpha3: "MYT", number: "175" },
		{ name: "Mexico", alpha2: "MX", alpha3: "MEX", number: "484" },
		{ name: "Micronesia (Federated States of)", alpha2: "FM", alpha3: "FSM", number: "583" },
		{ name: "Moldova (the Republic of)", alpha2: "MD", alpha3: "MDA", number: "498" },
		{ name: "Monaco", alpha2: "MC", alpha3: "MCO", number: "492" },
		{ name: "Mongolia", alpha2: "MN", alpha3: "MNG", number: "496" },
		{ name: "Montenegro", alpha2: "ME", alpha3: "MNE", number: "499" },
		{ name: "Montserrat", alpha2: "MS", alpha3: "MSR", number: "500" },
		{ name: "Morocco", alpha2: "MA", alpha3: "MAR", number: "504" },
		{ name: "Mozambique", alpha2: "MZ", alpha3: "MOZ", number: "508" },
		{ name: "Myanmar", alpha2: "MM", alpha3: "MMR", number: "104" },
		{ name: "Namibia", alpha2: "NA", alpha3: "NAM", number: "516" },
		{ name: "Nauru", alpha2: "NR", alpha3: "NRU", number: "520" },
		{ name: "Nepal", alpha2: "NP", alpha3: "NPL", number: "524" },
		{ name: "Netherlands", alpha2: "NL", alpha3: "NLD", number: "528" },
		{ name: "New Caledonia", alpha2: "NC", alpha3: "NCL", number: "540" },
		{ name: "New Zealand", alpha2: "NZ", alpha3: "NZL", number: "554" },
		{ name: "Nicaragua", alpha2: "NI", alpha3: "NIC", number: "558" },
		{ name: "Niger", alpha2: "NE", alpha3: "NER", number: "562" },
		{ name: "Nigeria", alpha2: "NG", alpha3: "NGA", number: "566" },
		{ name: "Niue", alpha2: "NU", alpha3: "NIU", number: "570" },
		{ name: "Norfolk Island", alpha2: "NF", alpha3: "NFK", number: "574" },
		{ name: "Northern Mariana Islands", alpha2: "MP", alpha3: "MNP", number: "580" },
		{ name: "Norway", alpha2: "NO", alpha3: "NOR", number: "578" },
		{ name: "Oman", alpha2: "OM", alpha3: "OMN", number: "512" },
		{ name: "Pakistan", alpha2: "PK", alpha3: "PAK", number: "586" },
		{ name: "Palau", alpha2: "PW", alpha3: "PLW", number: "585" },
		{ name: "Palestine, State of", alpha2: "PS", alpha3: "PSE", number: "275" },
		{ name: "Panama", alpha2: "PA", alpha3: "PAN", number: "591" },
		{ name: "Papua New Guinea", alpha2: "PG", alpha3: "PNG", number: "598" },
		{ name: "Paraguay", alpha2: "PY", alpha3: "PRY", number: "600" },
		{ name: "Peru", alpha2: "PE", alpha3: "PER", number: "604" },
		{ name: "Philippines", alpha2: "PH", alpha3: "PHL", number: "608" },
		{ name: "Pitcairn", alpha2: "PN", alpha3: "PCN", number: "612" },
		{ name: "Poland", alpha2: "PL", alpha3: "POL", number: "616" },
		{ name: "Portugal", alpha2: "PT", alpha3: "PRT", number: "620" },
		{ name: "Puerto Rico", alpha2: "PR", alpha3: "PRI", number: "630" },
		{ name: "Qatar", alpha2: "QA", alpha3: "QAT", number: "634" },
		{ name: "Republic of North Macedonia", alpha2: "MK", alpha3: "MKD", number: "807" },
		{ name: "Romania", alpha2: "RO", alpha3: "ROU", number: "642" },
		{ name: "Russian Federation", alpha2: "RU", alpha3: "RUS", number: "643" },
		{ name: "Rwanda", alpha2: "RW", alpha3: "RWA", number: "646" },
		{ name: "Réunion", alpha2: "RE", alpha3: "REU", number: "638" },
		{ name: "Saint Barthélemy", alpha2: "BL", alpha3: "BLM", number: "652" },
		{ name: "Saint Helena, Ascension and Tristan da Cunha", alpha2: "SH", alpha3: "SHN", number: "654" },
		{ name: "Saint Kitts and Nevis", alpha2: "KN", alpha3: "KNA", number: "659" },
		{ name: "Saint Lucia", alpha2: "LC", alpha3: "LCA", number: "662" },
		{ name: "Saint Martin (French part)", alpha2: "MF", alpha3: "MAF", number: "663" },
		{ name: "Saint Pierre and Miquelon", alpha2: "PM", alpha3: "SPM", number: "666" },
		{ name: "Saint Vincent and the Grenadines", alpha2: "VC", alpha3: "VCT", number: "670" },
		{ name: "Samoa", alpha2: "WS", alpha3: "WSM", number: "882" },
		{ name: "San Marino", alpha2: "SM", alpha3: "SMR", number: "674" },
		{ name: "Sao Tome and Principe", alpha2: "ST", alpha3: "STP", number: "678" },
		{ name: "Saudi Arabia", alpha2: "SA", alpha3: "SAU", number: "682" },
		{ name: "Senegal", alpha2: "SN", alpha3: "SEN", number: "686" },
		{ name: "Serbia", alpha2: "RS", alpha3: "SRB", number: "688" },
		{ name: "Seychelles", alpha2: "SC", alpha3: "SYC", number: "690" },
		{ name: "Sierra Leone", alpha2: "SL", alpha3: "SLE", number: "694" },
		{ name: "Singapore", alpha2: "SG", alpha3: "SGP", number: "702" },
		{ name: "Sint Maarten (Dutch part)", alpha2: "SX", alpha3: "SXM", number: "534" },
		{ name: "Slovakia", alpha2: "SK", alpha3: "SVK", number: "703" },
		{ name: "Slovenia", alpha2: "SI", alpha3: "SVN", number: "705" },
		{ name: "Solomon Islands", alpha2: "SB", alpha3: "SLB", number: "90" },
		{ name: "Somalia", alpha2: "SO", alpha3: "SOM", number: "706" },
		{ name: "South Africa", alpha2: "ZA", alpha3: "ZAF", number: "710" },
		{ name: "South Georgia and the South Sandwich Islands", alpha2: "GS", alpha3: "SGS", number: "239" },
		{ name: "South Sudan", alpha2: "SS", alpha3: "SSD", number: "728" },
		{ name: "Spain", alpha2: "ES", alpha3: "ESP", number: "724" },
		{ name: "Sri Lanka", alpha2: "LK", alpha3: "LKA", number: "144" },
		{ name: "Sudan", alpha2: "SD", alpha3: "SDN", number: "729" },
		{ name: "Suriname", alpha2: "SR", alpha3: "SUR", number: "740" },
		{ name: "Svalbard and Jan Mayen", alpha2: "SJ", alpha3: "SJM", number: "744" },
		{ name: "Sweden", alpha2: "SE", alpha3: "SWE", number: "752" },
		{ name: "Switzerland", alpha2: "CH", alpha3: "CHE", number: "756" },
		{ name: "Syrian Arab Republic", alpha2: "SY", alpha3: "SYR", number: "760" },
		{ name: "Taiwan (Province of China)", alpha2: "TW", alpha3: "TWN", number: "158" },
		{ name: "Tajikistan", alpha2: "TJ", alpha3: "TJK", number: "762" },
		{ name: "Tanzania, United Republic of", alpha2: "TZ", alpha3: "TZA", number: "834" },
		{ name: "Thailand", alpha2: "TH", alpha3: "THA", number: "764" },
		{ name: "Timor-Leste", alpha2: "TL", alpha3: "TLS", number: "626" },
		{ name: "Togo", alpha2: "TG", alpha3: "TGO", number: "768" },
		{ name: "Tokelau", alpha2: "TK", alpha3: "TKL", number: "772" },
		{ name: "Tonga", alpha2: "TO", alpha3: "TON", number: "776" },
		{ name: "Trinidad and Tobago", alpha2: "TT", alpha3: "TTO", number: "780" },
		{ name: "Tunisia", alpha2: "TN", alpha3: "TUN", number: "788" },
		{ name: "Turkey", alpha2: "TR", alpha3: "TUR", number: "792" },
		{ name: "Turkmenistan", alpha2: "TM", alpha3: "TKM", number: "795" },
		{ name: "Turks and Caicos Islands", alpha2: "TC", alpha3: "TCA", number: "796" },
		{ name: "Tuvalu", alpha2: "TV", alpha3: "TUV", number: "798" },
		{ name: "Uganda", alpha2: "UG", alpha3: "UGA", number: "800" },
		{ name: "Ukraine", alpha2: "UA", alpha3: "UKR", number: "804" },
		{ name: "United Arab Emirates", alpha2: "AE", alpha3: "ARE", number: "784" },
		{ name: "United Kingdom of Great Britain and Northern Ireland", alpha2: "GB", alpha3: "GBR", number: "826" },
		{ name: "United States Minor Outlying Islands", alpha2: "UM", alpha3: "UMI", number: "581" },
		{ name: "United States of America", alpha2: "US", alpha3: "USA", number: "840" },
		{ name: "Uruguay", alpha2: "UY", alpha3: "URY", number: "858" },
		{ name: "Uzbekistan", alpha2: "UZ", alpha3: "UZB", number: "860" },
		{ name: "Vanuatu", alpha2: "VU", alpha3: "VUT", number: "548" },
		{ name: "Venezuela (Bolivarian Republic of)", alpha2: "VE", alpha3: "VEN", number: "862" },
		{ name: "Viet Nam", alpha2: "VN", alpha3: "VNM", number: "704" },
		{ name: "Virgin Islands (British)", alpha2: "VG", alpha3: "VGB", number: "92" },
		{ name: "Virgin Islands (U.S.)", alpha2: "VI", alpha3: "VIR", number: "850" },
		{ name: "Wallis and Futuna", alpha2: "WF", alpha3: "WLF", number: "876" },
		{ name: "Western Sahara", alpha2: "EH", alpha3: "ESH", number: "732" },
		{ name: "Yemen", alpha2: "YE", alpha3: "YEM", number: "887" },
		{ name: "Zambia", alpha2: "ZM", alpha3: "ZMB", number: "894" },
		{ name: "Zimbabwe", alpha2: "ZW", alpha3: "ZWE", number: "716" },
		{ name: "Åland Islands", alpha2: "AX", alpha3: "ALA", number: "248" }
	]
