export default
	[
		{ code: "ALL", number: "8", name: "Albanian lek", symbol: "L", subunit: "qindarkë" },
		{ code: "DZD", number: "12", name: "Algerian dinar", symbol: "د.ج", subunit: "Santeem" },
		{ code: "ARS", number: "32", name: "Argentine peso", symbol: "$", subunit: "centavo" },
		{ code: "AUD", number: "36", name: "Australian dollar", symbol: "$", subunit: "cent" },
		{ code: "BSD", number: "44", name: "Bahamian dollar", symbol: "$", subunit: "cent" },
		{ code: "BHD", number: "48", name: "Bahraini dinar", symbol: ".د.ب", subunit: "fils" },
		{ code: "BDT", number: "50", name: "Bangladeshi taka", symbol: "৳", subunit: "paisa" },
		{ code: "AMD", number: "51", name: "Armenian dram", symbol: "դր.", subunit: "luma" },
		{ code: "BBD", number: "52", name: "Barbados dollar", symbol: "$", subunit: "cent" },
		{ code: "BMD", number: "60", name: "Bermudian dollar", symbol: "$", subunit: "cent" },
		{ code: "BTN", number: "64", name: "Bhutanese ngultrum", symbol: "Nu.", subunit: "chetrum" },
		{ code: "BOB", number: "68", name: "Boliviano", symbol: "Bs.", subunit: "centavo" },
		{ code: "BWP", number: "72", name: "Botswana pula", symbol: "P", subunit: "thebe" },
		{ code: "BZD", number: "84", name: "Belize dollar", symbol: "$", subunit: "cent" },
		{ code: "SBD", number: "90", name: "Solomon Islands dollar", symbol: "$", subunit: "cent" },
		{ code: "BND", number: "96", name: "Brunei dollar", symbol: "$", subunit: "sen" },
		{ code: "MMK", number: "104", name: "Myanma kyat", symbol: "Ks", subunit: "pya" },
		{ code: "BIF", number: "108", name: "Burundian franc", symbol: "Fr", subunit: "centime" },
		{ code: "KHR", number: "116", name: "Cambodian riel", symbol: "៛", subunit: "sen" },
		{ code: "CAD", number: "124", name: "Canadian dollar", symbol: "$", subunit: "cent" },
		{ code: "CVE", number: "132", name: "Cape Verde escudo", symbol: "Esc or $", subunit: "centavo" },
		{ code: "KYD", number: "136", name: "Cayman Islands dollar", symbol: "$", subunit: "cent" },
		{ code: "LKR", number: "144", name: "Sri Lankan rupee", symbol: "Rs", subunit: "cent" },
		{ code: "CLP", number: "152", name: "Chilean peso", symbol: "$", subunit: "centavo" },
		{ code: "CNY", number: "156", name: "Chinese yuan", symbol: "¥", subunit: "fen" },
		{ code: "COP", number: "170", name: "Colombian peso", symbol: "$", subunit: "centavo" },
		{ code: "KMF", number: "174", name: "Comoro franc", symbol: "Fr", subunit: "centime" },
		{ code: "CRC", number: "188", name: "Costa Rican colon", symbol: "₡", subunit: "cêntimo" },
		{ code: "HRK", number: "191", name: "Croatian kuna", symbol: "kn", subunit: "lipa" },
		{ code: "CUP", number: "192", name: "Cuban peso", symbol: "$", subunit: "centavo" },
		{ code: "CZK", number: "203", name: "Czech koruna", symbol: "Kč", subunit: "haléř" },
		{ code: "DKK", number: "208", name: "Danish krone", symbol: "kr", subunit: "øre" },
		{ code: "DOP", number: "214", name: "Dominican peso", symbol: "$", subunit: "centavo" },
		{ code: "ETB", number: "230", name: "Ethiopian birr", symbol: "Br", subunit: "santim" },
		{ code: "ERN", number: "232", name: "Eritrean nakfa", symbol: "Nfk", subunit: "cent" },
		{ code: "FKP", number: "238", name: "Falkland Islands pound", symbol: "£", subunit: "penny" },
		{ code: "FJD", number: "242", name: "Fiji dollar", symbol: "$", subunit: "cent" },
		{ code: "DJF", number: "262", name: "Djiboutian franc", symbol: "Fr", subunit: "centime" },
		{ code: "GMD", number: "270", name: "Gambian dalasi", symbol: "D", subunit: "butut" },
		{ code: "GIP", number: "292", name: "Gibraltar pound", symbol: "£", subunit: "penny" },
		{ code: "GTQ", number: "320", name: "Guatemalan quetzal", symbol: "Q", subunit: "centavo" },
		{ code: "GNF", number: "324", name: "Guinean franc", symbol: "Fr", subunit: "centime" },
		{ code: "GYD", number: "328", name: "Guyanese dollar", symbol: "$", subunit: "cent" },
		{ code: "HTG", number: "332", name: "Haitian gourde", symbol: "G", subunit: "centime" },
		{ code: "HNL", number: "340", name: "Honduran lempira", symbol: "L", subunit: "centavo" },
		{ code: "HKD", number: "344", name: "Hong Kong dollar", symbol: "$", subunit: "cent" },
		{ code: "HUF", number: "348", name: "Hungarian forint", symbol: "Ft", subunit: "fillér" },
		{ code: "ISK", number: "352", name: "Icelandic króna", symbol: "kr", subunit: "eyrir" },
		{ code: "INR", number: "356", name: "Indian rupee", symbol: "₹", subunit: "paisa" },
		{ code: "IDR", number: "360", name: "Indonesian rupiah", symbol: "Rp", subunit: "sen" },
		{ code: "IRR", number: "364", name: "Iranian rial", symbol: "﷼", subunit: "NULL" },
		{ code: "IQD", number: "368", name: "Iraqi dinar", symbol: "ع.د", subunit: "fils" },
		{ code: "ILS", number: "376", name: "Israeli new shekel", symbol: "₪", subunit: "agora" },
		{ code: "JMD", number: "388", name: "Jamaican dollar", symbol: "$", subunit: "cent" },
		{ code: "JPY", number: "392", name: "Japanese yen", symbol: "¥", subunit: "sen" },
		{ code: "KZT", number: "398", name: "Kazakhstani tenge", symbol: "₸", subunit: "tïın" },
		{ code: "JOD", number: "400", name: "Jordanian dinar", symbol: "د.ا", subunit: "piastre" },
		{ code: "KES", number: "404", name: "Kenyan shilling", symbol: "Sh", subunit: "cent" },
		{ code: "KPW", number: "408", name: "North Korean won", symbol: "₩", subunit: "chon" },
		{ code: "KRW", number: "410", name: "South Korean won", symbol: "₩", subunit: "jeon" },
		{ code: "KWD", number: "414", name: "Kuwaiti dinar", symbol: "د.ك", subunit: "fils" },
		{ code: "KGS", number: "417", name: "Kyrgyzstani som", symbol: "лв", subunit: "tyiyn" },
		{ code: "LAK", number: "418", name: "Lao kip", symbol: "₭", subunit: "att" },
		{ code: "LBP", number: "422", name: "Lebanese pound", symbol: "ل.ل", subunit: "piastre" },
		{ code: "LSL", number: "426", name: "Lesotho loti", symbol: "L", subunit: "sente" },
		{ code: "LRD", number: "430", name: "Liberian dollar", symbol: "$", subunit: "cent" },
		{ code: "LYD", number: "434", name: "Libyan dinar", symbol: "ل.د", subunit: "dirham" },
		{ code: "LTL", number: "440", name: "Lithuanian litas", symbol: "Lt", subunit: "centas" },
		{ code: "MOP", number: "446", name: "Macanese pataca", symbol: "P", subunit: "avo" },
		{ code: "MWK", number: "454", name: "Malawian kwacha", symbol: "MK", subunit: "tambala" },
		{ code: "MYR", number: "458", name: "Malaysian ringgit", symbol: "RM", subunit: "sen" },
		{ code: "MVR", number: "462", name: "Maldivian rufiyaa", symbol: ".ރ", subunit: "laari" },
		{ code: "MRO", number: "478", name: "Mauritanian ouguiya", symbol: "UM", subunit: "khoums" },
		{ code: "MUR", number: "480", name: "Mauritian rupee", symbol: "₨", subunit: "cent" },
		{ code: "MXN", number: "484", name: "Mexican peso", symbol: "$", subunit: "centavo" },
		{ code: "MNT", number: "496", name: "Mongolian tugrik", symbol: "₮", subunit: "möngö" },
		{ code: "MDL", number: "498", name: "Moldovan leu", symbol: "L", subunit: "ban" },
		{ code: "MAD", number: "504", name: "Moroccan dirham", symbol: "د.م.", subunit: "centime" },
		{ code: "OMR", number: "512", name: "Omani rial", symbol: "ر.ع.", subunit: "Baisa" },
		{ code: "NAD", number: "516", name: "Namibian dollar", symbol: "$", subunit: "cent" },
		{ code: "NPR", number: "524", name: "Nepalese rupee", symbol: "₨", subunit: "paisa" },
		{ code: "ANG", number: "532", name: "Netherlands Antillean guilder", symbol: "ƒ", subunit: "cent" },
		{ code: "AWG", number: "533", name: "Aruban florin", symbol: "ƒ", subunit: "cent" },
		{ code: "VUV", number: "548", name: "Vanuatu vatu", symbol: "Vt", subunit: "NULL" },
		{ code: "NZD", number: "554", name: "New Zealand dollar", symbol: "$", subunit: "cent" },
		{ code: "NIO", number: "558", name: "Nicaraguan córdoba", symbol: "C$", subunit: "centavo" },
		{ code: "NGN", number: "566", name: "Nigerian naira", symbol: "₦", subunit: "kobo" },
		{ code: "NOK", number: "578", name: "Norwegian krone", symbol: "kr", subunit: "øre" },
		{ code: "PKR", number: "586", name: "Pakistani rupee", symbol: "₨", subunit: "paisa" },
		{ code: "PAB", number: "590", name: "Panamanian balboa", symbol: "B/.", subunit: "centésimo" },
		{ code: "PGK", number: "598", name: "Papua New Guinean kina", symbol: "K", subunit: "toea" },
		{ code: "PYG", number: "600", name: "Paraguayan guaraní", symbol: "₲", subunit: "cêntimo" },
		{ code: "PEN", number: "604", name: "Peruvian nuevo sol", symbol: "S/.", subunit: "cêntimo" },
		{ code: "PHP", number: "608", name: "Philippine peso", symbol: "₱", subunit: "centavo" },
		{ code: "QAR", number: "634", name: "Qatari riyal", symbol: "ر.ق", subunit: "dirham" },
		{ code: "RUB", number: "643", name: "Russian rouble", symbol: "руб.", subunit: "kopek" },
		{ code: "RWF", number: "646", name: "Rwandan franc", symbol: "Fr", subunit: "centime" },
		{ code: "SHP", number: "654", name: "Saint Helena pound", symbol: "£", subunit: "penny" },
		{ code: "STD", number: "678", name: "São Tomé and Príncipe dobra", symbol: "Db", subunit: "cêntimo" },
		{ code: "SAR", number: "682", name: "Saudi riyal", symbol: "ر.س", subunit: "halala" },
		{ code: "SCR", number: "690", name: "Seychelles rupee", symbol: "₨", subunit: "cent" },
		{ code: "SLL", number: "694", name: "Sierra leonean leone", symbol: "Le", subunit: "cent" },
		{ code: "SGD", number: "702", name: "Singapore dollar", symbol: "$", subunit: "cent" },
		{ code: "VND", number: "704", name: "Vietnamese dong", symbol: "₫", subunit: "hào" },
		{ code: "SOS", number: "706", name: "Somali shilling", symbol: "Sh", subunit: "cent" },
		{ code: "ZAR", number: "710", name: "South African rand", symbol: "R", subunit: "cent" },
		{ code: "SSP", number: "728", name: "South Sudanese pound", symbol: "£", subunit: "piastre" },
		{ code: "SZL", number: "748", name: "Swazi lilangeni", symbol: "L", subunit: "cent" },
		{ code: "SEK", number: "752", name: "Swedish krona", symbol: "kr", subunit: "öre" },
		{ code: "CHF", number: "756", name: "Swiss franc", symbol: "Fr", subunit: "rappen" },
		{ code: "SYP", number: "760", name: "Syrian pound", symbol: "ل.س", subunit: "piastre" },
		{ code: "THB", number: "764", name: "Thai baht", symbol: "฿", subunit: "satang" },
		{ code: "TOP", number: "776", name: "Tongan paʻanga", symbol: "T$", subunit: "seniti" },
		{ code: "TTD", number: "780", name: "Trinidad and Tobago dollar", symbol: "$", subunit: "cent" },
		{ code: "AED", number: "784", name: "United Arab Emirates dirham", symbol: "د.إ", subunit: "fils" },
		{ code: "TND", number: "788", name: "Tunisian dinar", symbol: "د.ت", subunit: "millime" },
		{ code: "UGX", number: "800", name: "Ugandan shilling", symbol: "Sh", subunit: "cent" },
		{ code: "MKD", number: "807", name: "Macedonian denar", symbol: "ден", subunit: "deni" },
		{ code: "EGP", number: "818", name: "Egyptian pound", symbol: "ج.م", subunit: "piaster" },
		{ code: "GBP", number: "826", name: "Pound sterling", symbol: "£", subunit: "penny" },
		{ code: "TZS", number: "834", name: "Tanzanian shilling", symbol: "Sh", subunit: "cent" },
		{ code: "USD", number: "840", name: "United States dollar", symbol: "$", subunit: "cent" },
		{ code: "UYU", number: "858", name: "Uruguayan peso", symbol: "$", subunit: "centésimo" },
		{ code: "UZS", number: "860", name: "Uzbekistan som", symbol: "лв", subunit: "tiyin" },
		{ code: "WST", number: "882", name: "Samoan tala", symbol: "T", subunit: "sene" },
		{ code: "YER", number: "886", name: "Yemeni rial", symbol: "﷼", subunit: "fils" },
		{ code: "TWD", number: "901", name: "New Taiwan dollar", symbol: "$", subunit: "cent" },
		{ code: "CUC", number: "931", name: "Cuban convertible peso", symbol: "$", subunit: "centavo" },
		{ code: "TMT", number: "934", name: "Turkmenistani manat", symbol: "m", subunit: "tennesi" },
		{ code: "GHS", number: "936", name: "Ghanaian cedi", symbol: "₵", subunit: "pesewa" },
		{ code: "VEF", number: "937", name: "Venezuelan bolívar fuerte", symbol: "Bs F", subunit: "cêntimo" },
		{ code: "SDG", number: "938", name: "Sudanese pound", symbol: "£", subunit: "piastre" },
		{ code: "RSD", number: "941", name: "Serbian dinar", symbol: "дин.", subunit: "para" },
		{ code: "MZN", number: "943", name: "Mozambican metical", symbol: "MT", subunit: "centavo" },
		{ code: "AZN", number: "944", name: "Azerbaijani manat", symbol: "m", subunit: "qəpik" },
		{ code: "RON", number: "946", name: "Romanian new leu", symbol: "L", subunit: "ban" },
		{ code: "TRY", number: "949", name: "Turkish lira", symbol: "NULL", subunit: "kuruş" },
		{ code: "XAF", number: "950", name: "CFA franc BEAC", symbol: "Fr", subunit: "centime" },
		{ code: "XCD", number: "951", name: "East Caribbean dollar", symbol: "$", subunit: "cent" },
		{ code: "XOF", number: "952", name: "CFA franc BCEAO", symbol: "Fr", subunit: "centime" },
		{ code: "XPF", number: "953", name: "CFP franc", symbol: "Fr", subunit: "centime" },
		{ code: "ZMW", number: "967", name: "Zambian kwacha", symbol: "ZK", subunit: "ngwee" },
		{ code: "SRD", number: "968", name: "Surinamese dollar", symbol: "$", subunit: "cent" },
		{ code: "MGA", number: "969", name: "Malagasy ariary", symbol: "Ar", subunit: "iraimbilanja" },
		{ code: "AFN", number: "971", name: "Afghan afghani", symbol: "؋", subunit: "pul" },
		{ code: "TJS", number: "972", name: "Tajikistani somoni", symbol: "ЅМ", subunit: "diram" },
		{ code: "AOA", number: "973", name: "Angolan kwanza", symbol: "Kz", subunit: "cêntimo" },
		{ code: "BYR", number: "974", name: "Belarusian ruble", symbol: "Br", subunit: "kapyeyka" },
		{ code: "BGN", number: "975", name: "Bulgarian lev", symbol: "лв", subunit: "stotinka" },
		{ code: "CDF", number: "976", name: "Congolese franc", symbol: "Fr", subunit: "centime" },
		{ code: "BAM", number: "977", name: "Bosnia and Herzegovina convertible mark", symbol: "КМ", subunit: "fening" },
		{ code: "EUR", number: "978", name: "Euro", symbol: "€", subunit: "cent" },
		{ code: "UAH", number: "980", name: "Ukrainian hryvnia", symbol: "₴", subunit: "kopiyka" },
		{ code: "GEL", number: "981", name: "Georgian lari", symbol: "ლ", subunit: "tetri" },
		{ code: "PLN", number: "985", name: "Polish złoty", symbol: "zł", subunit: "grosz" },
		{ code: "BRL", number: "986", name: "Brazilian real", symbol: "R$", subunit: "centavo" },
	]
